### ISSUE TITLE
Admin UI, Angular compilation error with Vendure 1.1.3

### ISSUE THREAD

**Issue by nemo-js** [drewterry/vendure-favorites-plugin#25]
> Type 'FavoritesListComponent' is missing the following properties from type 'CustomFieldControl': readonly, config

If I add the following properties on FavoritesListComponent, it compiles
```
readonly = false;
config: CustomFieldConfigType;
```

**Comment by drewterry** [comment]
Nice, feel like opening a PR?

**Comment by nemo-js** [comment]
I have create a branch with the fix, but I cannot push it.

**Comment by drewterry** [comment]
Did you create a fork?

https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by nemo-js** [comment]
Thanks, I did, but then I noticed that the fix already exists in the code, but it is not published to npm

**Comment by drewterry** [comment]
Gotcha, it looks like `semantic-release` was not publishing updates because conventional commits weren't being enforced.  I updated the repo to use it and pushed a new release out.

**Comment by nemo-js** [comment]
Thank you very much
